version: 'latest'

services:
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - my-network
    depends_on:
      - server
      
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    command: pm2-runtime start ecosystem.config.cjs
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'
    networks:
      - my-network
    depends_on:
      - mongo

  mongo: 
    build:
      context: ./server/db
      dockerfile: Dockerfile
    container_name: db
    ports:
      - '27017:27017'
    networks:
      - my-network
  
  nginx:
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    links:
      - server:server
    networks:
      - my-network
networks:
  my-network:
    driver: bridge